### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by pravic** [mmstick/numtoa#13]
Here: https://github.com/mmstick/numtoa/blob/master/src/lib.rs#L241

Wouldn't it be better to write an universal implementation and just call it from generic impls?

**Comment by mmstick** [comment]
That's not possible because each implementation is specific to the size of the integer. Rust also doesn't support using integers in a generic fashion.

**Comment by master-hax** [comment]
there is https://crates.io/crates/num-traits that might be able to solve this
