### ISSUE TITLE
Share benchmark code

### ISSUE THREAD

**Issue by dtolnay** [mmstick/numtoa#4]
I see benchmark numbers in the readme but the code isn't in the repo. Could you share the code so I can reproduce those on my machine? Really what I am wondering is how the comparison changes if I do have an io::Write that I need to write to, as is the case in serde_json. With numtoa I would have to copy the bytes from my buffer over to the io::Write which I imagine would cut into the 8% advantage.

**Comment by mmstick** [comment]
This is the source code:

```rust
extern crate itoa;
extern crate numtoa;
extern crate time;

use numtoa::NumToA;
use std::fs::File;
use std::io::Write;
use std::mem;

fn main() {
    let mut null = File::open("/dev/null").unwrap();
    let mut bytes;

    let numtoa_start = time::precise_time_ns() / 1_000_000;
    let mut buffer: [u8; 20] = unsafe { mem::uninitialized() };
    for number in 0..10_000_000u64 {
        bytes = number.numtoa(10, &mut buffer);
        let _ = null.write(&buffer[bytes..]);
    }
    let numtoa_end = time::precise_time_ns() / 1_000_000;

    let std_start = time::precise_time_ns() / 1_000_000;
    for number in 0..10_000_000u64 {
        let _ = write!(&mut null, "{}", number);
    }
    let std_end = time::precise_time_ns() / 1_000_000;

    let itoa_start = time::precise_time_ns() / 1_000_000;
    for number in 0..10_000_000u64 {
        let _ = itoa::write(&mut null, number);
    }
    let itoa_end = time::precise_time_ns() / 1_000_000;

    println!("numtoa: {} ms", numtoa_end - numtoa_start);
    println!("itoa: {} ms", itoa_end - itoa_start);
    println!("std: {} ms", std_end - std_start);
}
```

Although I'm certain that the reason for the difference is that I'm also shipping a triple and quad digit lookup table.

**Comment by dtolnay** [comment]
Thanks! Interestingly, if I am writing into a Vec\<u8> rather than /dev/null then the results are reversed and itoa is 10% faster.

```rust
let mut null = Vec::new();

for number in 0..100_000_000u64 {
    null.clear();
    /* write */
}
```

```
numtoa: 995 ms
itoa: 866 ms
std: 2803 ms
```

This is a better model of what is happening in `serde_json::to_string` for example. I wonder what accounts for the difference!

**Comment by dtolnay** [comment]
I filed #5 in case you are interested in following up. I would love to use this crate in serde_json if it really is faster.
