### ISSUE TITLE
Formatting negative numbers requires reserving one extra byte of space

### ISSUE THREAD

**Issue by japaric** [mmstick/numtoa#8]
For instance the i16 number `-32768` fits in a 6 byte buffer but trying to format that number in a 6 byte buffer using numtoa results in a panic:

``` rust
extern crate numtoa;

use std::str;

use numtoa::NumToA;

fn main() {
    let mut buffer: [u8; 6] = *b"-32768";

    let start = (-32768_i16).numtoa(10, &mut buffer);

    println!("{}", str::from_utf8(&buffer[start..]).unwrap());
}
```

```
$ cargo run
thread 'main' panicked at 'attempt to subtract with overflow', /home/japaric/.cargo/registry/src/github.com-1ecc6299db9ec823/numtoa-0.0.7/src/lib.rs:231
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

But if you use a 7 byte buffer the operation succeeds. You don't see this behavior when formating positive integers: for example, formatting `65535_u16` works fine with a 5 byte buffer.

**Comment by mmstick** [comment]
That's odd, because the negative variant only uses six characters. Sounds like it is writing from the next to last digit, rather than the last.
